### ISSUE TITLE
callback from send just only pass one parameter

### ISSUE THREAD

**Issue by bloodchen** [MatterCloud/filepay#1]
Unlike doc said send shall pass two parameters
Send(config, function(err,hash){
});

But after some test, I found  Send only pass ONE parameter, either hash or err 

It shall be consistent.

**Comment by ALiberalVoluntarist** [comment]
I got the same problem. You can use the callback function in filepay.build, but it didn't work in filepay.send... It returned "undefined" instead of tx.id.

**Comment by ghost** [comment]
Working on a fix now...

**Comment by ghost** [comment]
Fixed. https://github.com/MatterCloud/filepay/commit/67796ab0c01bc288e11ed1aa547551021b05e949
